drop table if exists Shoes;

create table Shoes (
       id integer generated by default as identity,
        shoesBrandName varchar(30) not null,
        shoesDate integer,
        shoesName varchar(100) not null,
        shoesPrice integer not null,
        shoesSize integer not null,
        primary key (id)
);